Feature/rdm 12992 delete multi linked cases
hmcts/ccd-case-disposer pull request #14
Opened 2021-12-07 13:56 UTC by sem-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDM-12856
https://tools.hmcts.net/jira/browse/RDM-12992

### Change description ###
Refactor logic to identify cases due deletion and delete them.
Also implement functional tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-02-23 12:24 UTC, mattnayler requested changes
Only minor review comments.

2022-02-23 12:45 UTC, sem-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/ccd/config/TestApplicationConfiguration.java
> +            .password("ccd")
Resolved by commit efe65d45f515fec388a8874be3d2e1d34e0db209 under RDM-13045

2022-02-23 12:52 UTC, sem-hmcts commented on src/functionalTest/java/uk/gov/hmcts/reform/ccd/TestDataProvider.java
> +    }
No, I don't think we want to do that.  I think we want to, as much as possible, test the production code as a black box.  This is here to verify that the production code is doing what we want it to do.

2022-02-23 12:53 UTC, sem-hmcts commented on src/functionalTest/resources/scenarios/S-001.sql
> +        '2016-06-24 20:44:52.824'
We could but if we want to do it this way then I suggest we do it as part of RDM-13046

2022-02-25 13:52 UTC, mattnayler approved these changes
LGTM including merger of RDM-13046

2022-04-12 16:58 UTC, merged